version: 1.0.{build}
image: Visual Studio 2017
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
build_script:
- cmd: nuget pack src\GdaxApi\GdaxApi\GdaxApi.csproj -o artifacts\packages
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
- api_key:
    secure: AkrFDHjLDjvlcEeLtlkJBUBA3lbDyAlHl6kU2GtraS+Onl33xR2LOSYaZIHPpW39
  skip_symbols: true
install:
  - cmd: curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe
  - cmd: dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log
skip_commits:
  files:    
    - '**/*.md'